---
name: Build installation ISO image


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        # reference: https://nix.dev/tutorials/building-bootable-iso-image
        # other possible formats: https://github.com/nix-community/nixos-generators#supported-formats
        nix --extra-experimental-features "nix-command flakes" profile install github:nix-community/nixos-generators
        echo ::set-env name=ISO_PATH::$(nixos-generate --format iso --configuration ./nix/install-iso.nix -o result)
    - run: |
        echo "The ISO: ${{ env.ISO_PATH }}"